In [ ]:
import numpy as np

# Create a 2D array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# -1 thì sẽ reshape về 1 hàng 
reshaped_array = original_array.reshape(-1)

print("Original array (2D):")
print(original_array)
print("\nReshaped array (1D):")
print(reshaped_array)

In [40]:
import numpy as np

def non_max_suppression(boxes, scores, threshold):
    """
    Perform non-maximum suppression.

    Parameters:
    boxes (numpy.ndarray): Array of bounding boxes, each defined by [x1, y1, x2, y2].
    scores (numpy.ndarray): Array of confidence scores for each bounding box.
    threshold (float): Overlap threshold for suppression.

    Returns:
    numpy.ndarray: Indices of bounding boxes to keep.
    """
    if len(boxes) == 0:
        return []

    # Coordinates of bounding boxes
    x1 = boxes[:, 0]
    y1 = boxes[:, 1]
    x2 = boxes[:, 2]
    y2 = boxes[:, 3]

    # Compute area of bounding boxes
    areas = (x2 - x1 + 1) * (y2 - y1 + 1)

    # Sort by scores
    order = scores.argsort()[::-1]
    print(order)
    keep = []
    while order.size > 0:
        i = order[0]
        keep.append(i)

        # Compute IoU (Intersection over Union)
        xx1 = np.maximum(x1[i], x1[order[1:]])
        yy1 = np.maximum(y1[i], y1[order[1:]])
        xx2 = np.minimum(x2[i], x2[order[1:]])
        yy2 = np.minimum(y2[i], y2[order[1:]])

        w = np.maximum(0, xx2 - xx1 + 1)
        h = np.maximum(0, yy2 - yy1 + 1)

        intersection = w * h
        iou = intersection / (areas[i] + areas[order[1:]] - intersection)

        # Suppress bounding boxes with IoU over the threshold
        # --> lấy những giá trị cần giữ lại truyền vào order
        inds = np.where(iou >= threshold)[0]

        print("inds trước khi plus: ", inds)
        # cộng thêm 1 vì where trả về index xuất phát từ 0 , nhưng khi tính toán lại order[1:](chỉ mục bắt đầu = 1) , vậy nên cần + 1
        inds = inds + 1
        print("inds sau khi plus: ", inds)

        #  delete xóa theo chỉ mục , vì xài order[1:] lúc tính toán , nên khi xóa phải dựa theo inds
        order = np.delete(order, inds)

        # ở trên append vào keep nhưng chưa được xóa phía trên , dưới này xóa
        order = np.delete(order, 0)
        
    return keep


# Example usage
boxes = np.array([
        [12, 84, 140, 212],
        [24, 84, 152, 212],
        [36, 84, 164, 212],
        [12, 96, 140, 224],
        [24, 96, 152, 224]
])

scores = np.array([0.8, 1, 0.7, 0.9, 0.5])
threshold = 0.5

keep_indices = non_max_suppression(boxes, scores, threshold)
kept_boxes = boxes[keep_indices]

print("Indices of boxes to keep:", keep_indices)
print("Boxes to keep:")
print(kept_boxes)

[1 3 0 2 4]
inds trước khi plus:  [0 1 2 3]
inds sau khi plus:  [1 2 3 4]
Indices of boxes to keep: [1]
Boxes to keep:
[[ 24  84 152 212]]


In [46]:
order = np.array([1, 3, 0, 2, 4])
inds = np.array([0, 1, 2, 3])
print(inds + 1)
order = order[inds + 1]

[1 2 3 4]


In [ ]:
a_data = np.array([6, 5, 7, 1, 9, 2])
a_data = np.delete(a_data, 2) # xóa tại vị trí bằng 2

In [43]:
# xóa nhiều phần tử dựa vào start_index và end_index
a_data = np.array([6, 5, 7, 1, 9, 2])

# xóa phần tử thứ 1 và 2
start_index = 1
end_index = 3
data_prev = a_data[:start_index]
data_bef = a_data[end_index:]
a_data = np.concatenate((data_prev, data_bef))
print(a_data)

[6 1 9 2]


In [45]:
a_data = np.array([6, 5, 7, 1, 9, 2])

a_data = np.delete(a_data , np.arange(1,3))
print(a_data)

[6 1 9 2]


In [49]:
a_data = np.array([6, 5, 7, 1, 9, 2])

# trả về số lần phần tử 7 xuất hiện trong list

count = (a_data == 7).sum()
print(count)

1


In [51]:
#copy một array
a_data = np.array([6, 5, 7, 1, 9, 2])
data = a_data.copy()
print(data)

[6 5 7 1 9 2]


In [52]:
print(len(a_data))

print(np.min(a_data))

print(np.max(a_data))

print(a_data.shape)

6
1
9
(6,)


In [53]:
arr1 = np.array([6, 1, 7])

for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 6
(1,) 1
(2,) 7


In [55]:
a = np.array([1, 2, 3, 4, 5])
print(a[[1, 3]])

[2 4]


In [56]:
a = np.array([9,1,3,8,2])
print(a[a > 3])

[9 8]


In [59]:
arr = np.array([[1,2],[3,4],[5,6]])

# -1 giúp tự động reshape cột, thay vì tự tìm số cột cho hợp lý
print(arr.reshape(2,-1))


[[1 2 3]
 [4 5 6]]


In [60]:
#Flattening: Convert a multi-dimensional array into 1D array

arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.flatten())

[1 2 3 4 5 6]


In [62]:
a = np.array([1, 2])
b = np.array([3, 4])

print(np.concatenate((a, b)))

[1 2 3 4]


In [63]:
a = np.array([[1, 2],[3,4],[5,6]])
b = np.array([1, 2])

# Broadcasting in action: adding the 1D array 'b' to each row of the 2D array

result = a + b
print(result)

[[2 4]
 [4 6]
 [6 8]]


In [64]:
# NumPy vectorization involves performing mathematical operations on entire arrays, 
# eliminating the need to loop through individual
# elements.
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

result = a * b

print(result)

[ 5 12 21 32]


In [87]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a.ndim)

a1 = a.reshape((2, -1), order="C")
print(a1)

a2 = a.reshape((2, -1), order="F")
print(a2)

1
[[1 2 3 4]
 [5 6 7 8]]
[[1 3 5 7]
 [2 4 6 8]]
