Lý thuyết

In [14]:
import numpy as np
height = 3
width = 2

A = np.array([[1, 0],
              [0, -1]])
img = np.arange(6).reshape(height, width)
print("before flip : \n", img)
p = np.array([0, height - 1])
output = np.zeros((height, width))
for x2 in range(height):
    for x1 in range(width):
        v = np.array([x1, x2])
        color = img[x2, x1]
        new_x1, new_x2 = A.dot(v) + p
        output[new_x2, new_x1] = color
        
print("after flip : \n", output.astype(int))

before flip : 
 [[0 1]
 [2 3]
 [4 5]]
after flip : 
 [[4 5]
 [2 3]
 [0 1]]


In [40]:
# remove for
height = 3
width = 2

A = np.array([[1, 0],
              [0, -1]])
p = np.array([0, height - 1]).reshape(2, 1)
img = np.arange(6).reshape(height, width)
output = np.zeros_like(img)

# Tạo ma trận tọa độ
# np.meshgrid tạo ma trận tọa độ x1 và x2.
x1, x2 = np.meshgrid(np.arange(width), np.arange(height))

# Chuyển ma trận tọa độ thành các vector
# np.vstack kết hợp x1 và x2 thành các vector tọa độ.
vectors = np.vstack([x1.ravel(), x2.ravel()])
print("before flipped x1-x2 : \n", vectors)
print("before flipped img : \n", img)

print()

flipped_loc = A.dot(vectors) + p

x1_x2 = list(zip(vectors[0], vectors[1]))
newx1_newx2 = list(zip(flipped_loc[0], flipped_loc[1]))

for i in range(len(x1_x2)):
    x1, x2 = x1_x2[i]
    new_x1, new_x2 = newx1_newx2[i]

    output[new_x2, new_x1] = img[x2, x1]

print("after flipped x1-x2 : \n", flipped_loc)
print("after flipped img : \n", output)

before flipped x1-x2 : 
 [[0 1 0 1 0 1]
 [0 0 1 1 2 2]]
before flipped img : 
 [[0 1]
 [2 3]
 [4 5]]

after flipped x1-x2 : 
 [[0 1 0 1 0 1]
 [2 2 1 1 0 0]]
after flipped img : 
 [[4 5]
 [2 3]
 [0 1]]


In [23]:
import cv2
image = cv2.imread('./image/nature_gray.png')
height, width, depth = image.shape
A = np.array([[1, 0],
              [0, -1]])
p = np.array([0, height - 1])

output = np.zeros_like(image)

for x2 in range(height):
    for x1 in range(width):
        v = np.array([x1, x2])
        color = image[x2, x1]
        new_x1, new_x2 = A.dot(v) + p

        output[new_x2, new_x1] = color

output_filename = './image/flipped_image.png'
cv2.imwrite(output_filename, output)

True

In [54]:
# flipped tọa độ vertical  kh cần xài for
import cv2
image = cv2.imread('./image/nature_gray.png')
height, width, depth = image.shape
A = np.array([[1, 0],
              [0, -1]])
p = np.array([0, height - 1]).reshape(2, 1)
output = np.zeros_like(image)

# Tạo ma trận tọa độ
# np.meshgrid tạo ma trận tọa độ x1 và x2.
x1, x2 = np.meshgrid(np.arange(width), np.arange(height))

# Chuyển ma trận tọa độ thành các vector
# np.vstack kết hợp x1 và x2 thành các vector tọa độ.
vectors = np.vstack([x1.ravel(), x2.ravel()])

flipped_loc = A.dot(vectors) + p

# cách 1
# x1_x2 = list(zip(vectors[0], vectors[1]))
# newx1_newx2 = list(zip(flipped_loc[0], flipped_loc[1]))

# for i in range(len(x1_x2)):
#     x_1, x_2 = x1_x2[i]
#     new_x1, new_x2 = newx1_newx2[i]
#     output[new_x2, new_x1] = image[x_2, x_1]

# cách 2:
output[flipped_loc[1], flipped_loc[0]] = image[x2.ravel(), x1.ravel()]

output_filename = './image/flipped_image2.png'
cv2.imwrite(output_filename, output)

True

In [56]:
# flipped tọa độ horizontal kh cần xài for
import cv2
image = cv2.imread('./image/nature_gray.png')
height, width, depth = image.shape
A = np.array([[-1, 0],
              [0, 1]])
p = np.array([width - 1, 0]).reshape(2, 1)
output = np.zeros_like(image)

# Tạo ma trận tọa độ
# np.meshgrid tạo ma trận tọa độ x1 và x2.
x1, x2 = np.meshgrid(np.arange(width), np.arange(height))

# Chuyển ma trận tọa độ thành các vector
# np.vstack kết hợp x1 và x2 thành các vector tọa độ.
vectors = np.vstack([x1.ravel(), x2.ravel()])

flipped_loc = A.dot(vectors) + p

# cách 1:
# x1_x2 = list(zip(vectors[0], vectors[1]))
# newx1_newx2 = list(zip(flipped_loc[0], flipped_loc[1]))

# for i in range(len(x1_x2)):
#     x_1, x_2 = x1_x2[i]
#     new_x1, new_x2 = newx1_newx2[i]
#     output[new_x2, new_x1] = image[x_2, x_1]

# cách 2:
output[flipped_loc[1], flipped_loc[0]] = image[x2.ravel(), x1.ravel()]

output_filename = './image/flipped_image_horizontal.png'
cv2.imwrite(output_filename, output)

True

Least Squares Estimation

In [61]:
import numpy as np

area = np.array([[6.7, 1],
              [4.6, 1],
              [3.5, 1],
              [5.5, 1]])

price = np.array([9.1, 5.9, 4.6, 6.7])

print(area)
print(area.T)
print(price)

[[6.7 1. ]
 [4.6 1. ]
 [3.5 1. ]
 [5.5 1. ]]
[[6.7 4.6 3.5 5.5]
 [1.  1.  1.  1. ]]
[9.1 5.9 4.6 6.7]


In [69]:
areaT_dot_area = (area.T).dot(area)

# Tính định thức
det_area = np.linalg.det(areaT_dot_area)

print("Định thức của ma trận area là:", det_area)

if det_area == 0:
    print("Kh có ma trận nghịch đảo area => phương trình vô nghiệm")

inv_areaT_dot_area = np.linalg.inv(areaT_dot_area)
print("Ma trận nghịch đảo của areaT_dot_area là:\n", inv_areaT_dot_area)


areaT_dot_price = (area.T).dot(price) 
print("Ma trận của areaT_dot_price là:\n", areaT_dot_price)

x = inv_areaT_dot_area.dot(areaT_dot_price)

print(x)

print(f"Vậy ta có phương trình: y = {x[0]}*x {x[1]}")

Định thức của ma trận area là: 22.109999999999914
Ma trận nghịch đảo của areaT_dot_area là:
 [[ 0.18091361 -0.91813659]
 [-0.91813659  4.90954319]]
Ma trận của areaT_dot_price là:
 [141.06  26.3 ]
[ 1.37268204 -0.39136137]
Vậy ta có phương trình: y = 1.3726820443238337*x -0.3913613749434946


In [2]:
import numpy as np
import cv2
import matplotlib.pyplot as plt


# read a color image
img1 = cv2.imread('./image/sign1.png')
img1 = cv2.resize(img1, (100, 100))

img2 = cv2.imread('./image/sign2.png')
img2 = cv2.resize(img2, (100, 100))

img3 = cv2.imread('./image/sign3.png')
img3 = cv2.resize(img3, (100, 100))

img4 = cv2.imread('./image/sign4.png')
img4 = cv2.resize(img4, (100, 100))


Using L1 and Cosine Similarity : TrafficSign

In [10]:
img1_2 = np.sum(np.abs(img1 - img2)) / (100 * 100 * 3)
img1_3 = np.sum(np.abs(img1 - img3)) / (100 * 100 * 3)
img1_4 = np.sum(np.abs(img1 - img4)) / (100 * 100 * 3)


print("image1 with image2 :", img1_2)
print("image1 with image3 :", img1_3)
print("image1 with image4 :", img1_4)

image1 with image2 : 50.618766666666666
image1 with image3 : 171.84026666666668
image1 with image4 : 90.49526666666667


In [13]:
img1_flatten = img1.flatten().astype(np.float64)
img2_flatten = img2.flatten().astype(np.float64)
img3_flatten = img3.flatten().astype(np.float64)
img4_flatten = img4.flatten().astype(np.float64)

img1_2 = (img1_flatten.dot(img2_flatten)) / (np.linalg.norm(img1_flatten) * np.linalg.norm(img2_flatten))
img1_3 = (img1_flatten.dot(img3_flatten)) / (np.linalg.norm(img1_flatten) * np.linalg.norm(img3_flatten))
img1_4 = (img1_flatten.dot(img4_flatten)) / (np.linalg.norm(img1_flatten) * np.linalg.norm(img4_flatten))


print("image1 with image2 :", img1_2)
print("image1 with image3 :", img1_3)
print("image1 with image4 :", img1_4)

image1 with image2 : 0.9547094275020529
image1 with image3 : 0.5750955260394579
image1 with image4 : 0.9669706203695292


**KNN Algorithm** 

In [45]:
import pandas as pd

df = pd.read_csv('./data/iris_2D.csv')
data = df.to_numpy()
x_test = (2.4, 0.8)
N = 3
length_width = data[:,0:2]
label = data[:, 2].astype(np.int8)
distance_euclid = np.sqrt(np.sum(np.abs(length_width - x_test)**2, axis=-1))

sorted_distance = sorted(list(zip(label, distance_euclid)), key=lambda x : x[1])
KNN = [data[0] for data in sorted_distance][:N]
# Đếm số lượng các nhãn trong KNN
label_count = [(label, KNN.count(label)) for label in np.unique(label)]
max_label = max(label_count,key= lambda count : count[1])
print(f"Với x_test(2.4, 0.8) thì có nhãn {max_label[0]}")

Với x_test(2.4, 0.8) thì có nhãn 0
