In [1]:
import numpy as np

In [4]:
# tạo mảng 3x3 toàn số 1
arr = np.ones((3, 3))
print(arr)

#  so sánh từng giá trị trong matrix và trả về matrix bool chứa kết quả
arr = np.ones((3, 3)) > 0
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [29]:
# tạo ma trận đơn vị 3x3
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
arr = np.arange(0, 10)
print (arr[arr % 2 == 1])

[1 3 5 7 9]


In [7]:
arr = np.arange(0, 10) 
arr[arr % 2 == 0] = -1
print(arr)

[-1  1 -1  3 -1  5 -1  7 -1  9]


In [8]:
arr = np.arange(0, 10)

# truyền -1 để tự tính số cột , mình khỏi phải ước tính
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
# Hàm repeat trong NumPy được sử dụng để lặp lại các phần tử của một mảng theo một cách xác định.

arr = np.array([1, 2, 3])

# Lặp lại mỗi phần tử 2 lần
repeated_arr = np.repeat(arr, 2)
print(repeated_arr)

[1 1 2 2 3 3]


In [14]:
arr = np.array([[1, 2], [3, 4]])

# Lặp lại mảng 2 lần dọc theo trục hàng và 3 lần dọc theo trục cột
tiled_arr = np.tile(arr, (2, 3))

print("Mảng ban đầu:")
print(arr)
print("\nMảng sau khi lặp lại 2 lần dọc theo trục 0, 1 lần dọc theo trục 1, và 3 lần dọc theo trục 2:")
print(tiled_arr)

Mảng ban đầu:
[[1 2]
 [3 4]]

Mảng sau khi lặp lại 2 lần dọc theo trục 0, 1 lần dọc theo trục 1, và 3 lần dọc theo trục 2:
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [16]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Lặp lại mảng 2 lần dọc theo trục 0, 1 lần dọc theo trục 1, và 3 lần dọc theo trục 2
tiled_arr = np.tile(arr, (2, 2, 3))

print("Mảng ban đầu:")
print(arr)
print("\nMảng sau khi lặp lại 2 lần dọc theo trục 0, 1 lần dọc theo trục 2, và 3 lần dọc theo trục 2:")
print(tiled_arr)

Mảng ban đầu:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Mảng sau khi lặp lại 2 lần dọc theo trục 0, 1 lần dọc theo trục 2, và 3 lần dọc theo trục 2:
[[[1 2 1 2 1 2]
  [3 4 3 4 3 4]
  [1 2 1 2 1 2]
  [3 4 3 4 3 4]]

 [[5 6 5 6 5 6]
  [7 8 7 8 7 8]
  [5 6 5 6 5 6]
  [7 8 7 8 7 8]]

 [[1 2 1 2 1 2]
  [3 4 3 4 3 4]
  [1 2 1 2 1 2]
  [3 4 3 4 3 4]]

 [[5 6 5 6 5 6]
  [7 8 7 8 7 8]
  [5 6 5 6 5 6]
  [7 8 7 8 7 8]]]


In [17]:
# Hàm Python với ba tham số
def myfunc(a, b, c):
    return a + b * c


# Vectơ hóa hàm
vectorized_func = np.vectorize(myfunc)

# Tạo các mảng NumPy
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = np.array([0.1, 0.2, 0.3, 0.4])

# Áp dụng hàm vectơ hóa cho các mảng
result = vectorized_func(a, b, c)

print("\nKết quả sau khi áp dụng hàm vectơ hóa:")
print(result)


Kết quả sau khi áp dụng hàm vectơ hóa:
[ 2.  6. 12. 20.]


In [18]:
a = np.array([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array([6 ,3 ,4 ,8 ,9 ,7 ,1])

#  so sánh từng phần tử trong mảng tương ứng theo index
print(a > b)

[False  True  True False False False  True]


In [19]:
# numpy.where(condition, [x, y])
# Tham số:
# condition: Một biểu thức điều kiện. Đây là mảng Boolean hoặc điều kiện mà bạn muốn kiểm tra.
# x: (Tùy chọn) Các phần tử để chọn từ nếu điều kiện là True.
# y: (Tùy chọn) Các phần tử để chọn từ nếu điều kiện là False.
a = np.array([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array([6 ,3 ,4 ,8 ,9 ,7 ,1])

print ("Result ",np.where(a <b, b, a))

 Result  [6 7 9 8 9 7 5]


In [1]:
# Cách nhân vô hướng trong numpy, lấy từng hàng ở E : [2.9, 2.4, 1.0, 0.2, 9.2] * cột ở Wq([7.5, -3.2, 9.1, -5.3, 8.9])
# lấy từng hàng ở matrix1 ra thì sẽ biến nó thành hàng dọc như dưới

# [2.9]
# |2.4|
# |1.0| *  [2.9, 2.4, 1.0, 0.2, 9.2]
# |0.2|
# |9.2]

In [18]:
import numpy as np
E = np.array([
    [2.9, 2.4, 1.0, 0.2, 9.2],
    [1.2, 3.4, 2.1, 8.2, 0.2],
    [4.9, 1.4, 7.0, 2.2, 3.2],
    [5.1, 3.2, 8.0, 4.2, 6.2],
    [0.9, 2.8, 7.1, 0.3, 1.2]
])

WQ = np.array([
    [7.5, -3.2, 9.1, -5.3, 8.9],
    [-9.6, -3.0, 7.0, 9.5, -0.4],
    [-5.5, -8.0, 7.2, 9.4, 8.0],
    [-8.8, 4.5, -9.7, 5.4, -7.0],
    [4.5, -4.5, -7.3, -8.8, 3.9]
])
result = np.dot(E, WQ)

print("Kết quả của phép nhân ma trận E với WQ:\n", result)
# 

Kết quả của phép nhân ma trận E với WQ:
 [[  32.85  -64.98  -18.71  -63.05   67.33]
 [-106.45    5.16  -31.16   88.2   -30.5 ]
 [ -20.15  -80.38   60.09   36.85   96.13]
 [ -45.53  -98.92   40.41   46.69  102.89]
 [ -56.42  -72.13   67.24   79.63   66.27]]


In [13]:
import pandas as pd
import numpy as np

temp = pd.read_csv("temperature-1d.csv" , index_col=0).to_numpy()
temp = temp.reshape(-1, 24)

# compute mean for each 24 data points
mean_24 = np.mean(temp, axis=1)

# 1 phần tử trong cột lặp lại 24 lần
mean_24_rep = np.repeat(mean_24, 24)
print(mean_24_rep)

[12.62685185 12.62685185 12.62685185 12.62685185 12.62685185 12.62685185
 12.62685185 12.62685185 12.62685185 12.62685185 12.62685185 12.62685185
 12.62685185 12.62685185 12.62685185 12.62685185 12.62685185 12.62685185
 12.62685185 12.62685185 12.62685185 12.62685185 12.62685185 12.62685185
 14.18148148 14.18148148 14.18148148 14.18148148 14.18148148 14.18148148
 14.18148148 14.18148148 14.18148148 14.18148148 14.18148148 14.18148148
 14.18148148 14.18148148 14.18148148 14.18148148 14.18148148 14.18148148
 14.18148148 14.18148148 14.18148148 14.18148148 14.18148148 14.18148148
 12.37453704 12.37453704 12.37453704 12.37453704 12.37453704 12.37453704
 12.37453704 12.37453704 12.37453704 12.37453704 12.37453704 12.37453704
 12.37453704 12.37453704 12.37453704 12.37453704 12.37453704 12.37453704
 12.37453704 12.37453704 12.37453704 12.37453704 12.37453704 12.37453704
  8.37060185  8.37060185  8.37060185  8.37060185  8.37060185  8.37060185
  8.37060185  8.37060185  8.37060185  8.37060185  8

In [49]:
# one-hot encoding
def eda_petal(row):
    row["species"] = np.where(unique_sp == row['species'])[0][0]
    return row
petal = pd.read_csv("iris.csv", index_col=0)
unique_sp = np.array(petal['species'].unique())
eda_petal = petal.apply(eda_petal, axis="columns").to_numpy()
eda_petal_sp = eda_petal[:, -1].astype(int)

print("labels after encoding : \n",eda_petal_sp)

nums_labels = unique_sp.shape[0]
nums_samples = eda_petal_sp.shape[0]
labels_onehot = np.zeros((nums_samples, nums_labels))
labels_onehot[np.arange(nums_samples), eda_petal_sp] = 1

print("Result after one-hot : \n" ,labels_onehot)

labels after encoding : 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Result after one-hot : 
 [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1.

In [62]:
# soft_max
data = np.array([1, 2, 3])
data_exp = np.exp(data)

sum_data_exp = np.sum(data_exp, axis=0)
result = data_exp / sum_data_exp

print(result)

[0.09003057 0.24472847 0.66524096]


In [59]:
# Đọc dữ liệu từ tệp (tên tệp được đại diện bởi ...).
# Dữ liệu sẽ được chuyển đổi thành kiểu float.
# Các giá trị trong tệp được phân tách bởi dấu phẩy (,).
# Bỏ qua dòng đầu tiên trong tệp (dòng tiêu đề).
# Chỉ đọc các cột có chỉ mục 0, 1, 2, và 3 (các cột sepal_length, sepal_width, petal_length, petal_width).

# lấy các đặc trưng lưu vào X
X = np.genfromtxt(fname="iris.csv", dtype=float, delimiter=',' ,usecols=[0, 1, 2, 3], skip_header=1)

# lấy labels lưu vào Y
Y = np.genfromtxt(fname="iris.csv", dtype=str, delimiter=',' , usecols=4, skip_header=1)

labels = np.unique(Y)

#  thay chuỗi bằng số
for i in range(len(labels)):
    Y = np.char.replace(Y, labels[i], str(i))
Y = Y.astype(int)
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
