### Khởi tạo embedding

In [54]:
import torch.nn as nn
import torch

vocab_size = 3
embed_dim = 5
hidden_dim = 3
embedding = nn.Embedding(vocab_size, embed_dim)
print(embedding.weight)

Parameter containing:
tensor([[-0.0589, -0.0076,  0.9485,  0.4967, -0.1190],
        [ 1.3687,  0.2505, -1.3363, -2.1836, -0.0737],
        [ 1.1634, -0.1850,  0.3644,  2.2584, -0.0577]], requires_grad=True)


### torch.randint(low, high, size, *, generator=None, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False)
- low: Giá trị tối thiểu (bao gồm cả giá trị này) của các số nguyên được tạo.
- high: Giá trị tối đa (không bao gồm giá trị này) của các số nguyên được tạo.
- size: Kích thước của tensor đầu ra (dạng tuple, ví dụ (2, 3))

In [55]:
data = torch.randint(0, vocab_size, (1, 3), dtype=torch.long)
data

tensor([[2, 0, 0]])

In [56]:
output = embedding(data)
output

tensor([[[ 1.1634, -0.1850,  0.3644,  2.2584, -0.0577],
         [-0.0589, -0.0076,  0.9485,  0.4967, -0.1190],
         [-0.0589, -0.0076,  0.9485,  0.4967, -0.1190]]],
       grad_fn=<EmbeddingBackward0>)

### Create RNNs

In [57]:
import torch.nn as nn

rnn = nn.RNN(embed_dim, hidden_dim, batch_first=True)
num_params = sum(p.numel() for p in rnn.parameters())
print(f"Number of parameters in RNN: {num_params}")

Number of parameters in RNN: 30


In [62]:
import torch.nn as nn

rnn = nn.RNN(embed_dim, hidden_dim, batch_first=True)
rnn_output, rnn_hidden = rnn(output)
print(rnn_output.shape)
print(rnn_hidden.shape)

torch.Size([1, 3, 3])
torch.Size([1, 1, 3])


In [63]:
print("Lấy toàn bộ kết quả RNNs", rnn_output)

Lấy toàn bộ kết quả RNNs tensor([[[-0.3662,  0.4203,  0.2592],
         [-0.3691,  0.2774, -0.0576],
         [-0.4579,  0.2936, -0.1061]]], grad_fn=<TransposeBackward1>)


In [64]:
print("Lấy kết quả cuối của RNNs", rnn_hidden) 
print("Lấy kết quả cuối của RNNs", rnn_hidden[-1,: ,: ])

Lấy kết quả cuối của RNNs tensor([[[-0.4579,  0.2936, -0.1061]]], grad_fn=<StackBackward0>)
Lấy kết quả cuối của RNNs tensor([[-0.4579,  0.2936, -0.1061]], grad_fn=<SliceBackward0>)
