In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(0)

class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, padding=0, bias=True)
        self.conv2 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, padding=0, bias=True)

    def forward(self, x):
        x = nn.ReLU()(self.conv1(x))
        x = self.conv2(x)
        return x

net = SimpleCNN()

noise_img = torch.randn(1, 1, 7, 7)
noise_img = nn.Parameter(noise_img)

target_data = torch.tensor([
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0],
    [0, 1, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0]
], dtype=torch.float32).unsqueeze(0).unsqueeze(0)

criterion = nn.MSELoss()
optimizer = optim.Adam([noise_img], lr=0.01)

conv1_w_before = net.conv1.weight.clone().detach()
conv1_b_before = net.conv1.bias.clone().detach()
conv2_w_before = net.conv2.weight.clone().detach()
conv2_b_before = net.conv2.bias.clone().detach()

In [ ]:
num_epochs = 500

for epoch in range(num_epochs):
    optimizer.zero_grad()

    noise_img_feature = net(noise_img)
    target_img_feature = net(target_data)

    loss = criterion(noise_img_feature, target_img_feature)

    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.6f}")

conv1_w_after = net.conv1.weight.clone().detach()
conv1_b_after = net.conv1.bias.clone().detach()
conv2_w_after = net.conv2.weight.clone().detach()
conv2_b_after = net.conv2.bias.clone().detach()

Epoch [10/500], Loss: 0.060196
Epoch [20/500], Loss: 0.045720
Epoch [30/500], Loss: 0.035025
Epoch [40/500], Loss: 0.028242
Epoch [50/500], Loss: 0.023416
Epoch [60/500], Loss: 0.019798
Epoch [70/500], Loss: 0.016487
Epoch [80/500], Loss: 0.013697
Epoch [90/500], Loss: 0.011230
Epoch [100/500], Loss: 0.009263
Epoch [110/500], Loss: 0.007724
Epoch [120/500], Loss: 0.006497
Epoch [130/500], Loss: 0.005558
Epoch [140/500], Loss: 0.004793
Epoch [150/500], Loss: 0.004155
Epoch [160/500], Loss: 0.003605
Epoch [170/500], Loss: 0.003134
Epoch [180/500], Loss: 0.002727
Epoch [190/500], Loss: 0.002373
Epoch [200/500], Loss: 0.002075
Epoch [210/500], Loss: 0.001820
Epoch [220/500], Loss: 0.001599
Epoch [230/500], Loss: 0.001410
Epoch [240/500], Loss: 0.001275
Epoch [250/500], Loss: 0.001177
Epoch [260/500], Loss: 0.001099
Epoch [270/500], Loss: 0.001037
Epoch [280/500], Loss: 0.000986
Epoch [290/500], Loss: 0.000942
Epoch [300/500], Loss: 0.000904
Epoch [310/500], Loss: 0.000871
Epoch [320/500], 

In [2]:
print("Trọng số của conv1.weight trước và sau:")
print("Trước:")
print(conv1_w_before)
print("Sau:")
print(conv1_w_after)

print("\nTrọng số cảu conv1.bias trước và sau:")
print("Trước:")
print(conv1_b_before)
print("Sau:")
print(conv1_b_after)

print("\nTrọng số conv2.weight trước và sau:")
print("Trước:")
print(conv2_w_before)
print("Sau:")
print(conv2_w_after)

print("\nTrọng số conv2.bias trước và sau:")
print("Trước:")
print(conv2_b_before)
print("Sau:")
print(conv2_b_after)

noise_img_final = noise_img.detach()
noise_feature_final = net(noise_img_final).detach()
target_feature_final = net(target_data).detach()

print("\nNoise_img ban đầu được update thành (7x7):")
print(noise_img_final[0, 0])

print("\nFeature cuối của noise_img (sau CNN):")
print(noise_feature_final[0, 0])

print("\nFeature cuối của target_img (sau CNN):")
print(target_feature_final[0, 0])

Trọng số của conv1.weight trước và sau:
Trước:
tensor([[[[-0.0025,  0.1788, -0.2743],
          [-0.2453, -0.1284,  0.0894],
          [-0.0066,  0.2643, -0.0296]]]])
Sau:


NameError: name 'conv1_w_after' is not defined

In [ ]:
print(target_data)

tensor([[[[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 1., 1., 0., 0., 0.],
          [0., 1., 0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.]]]])


In [3]:
print(noise_img)

Parameter containing:
tensor([[[[ 0.5988, -1.5551, -0.3414,  1.8530,  0.4681, -0.1577,  1.4437],
          [ 0.2660,  1.3894,  1.5863,  0.9463, -0.8437,  0.9318,  1.2590],
          [ 2.0050,  0.0537,  0.4397,  0.1124,  0.6408,  0.4412, -0.2159],
          [-0.7425,  0.5627,  0.2596,  0.5229,  2.3022, -1.4689, -1.5867],
          [ 1.2032,  0.0845, -1.2001, -0.0048, -0.2303,  2.5672, -0.4731],
          [ 0.3356,  1.5091,  2.0820,  1.7067,  2.3804, -1.1256,  1.1149],
          [-0.1407,  0.8058,  0.3276, -0.7607, -1.5991,  0.0185, -0.7504]]]],
       requires_grad=True)
