In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(0)

class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, padding=0, bias=True)
        self.conv2 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, padding=0, bias=True)

    def forward(self, x):
        x = nn.ReLU()(self.conv1(x))
        x = self.conv2(x)
        return x

net = SimpleCNN()

noise_img = torch.randn(1, 1, 7, 7)
noise_img = nn.Parameter(noise_img)

target_data = torch.tensor([
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0],
    [0, 1, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0]
], dtype=torch.float32).unsqueeze(0).unsqueeze(0)

criterion = nn.MSELoss()
optimizer = optim.Adam([noise_img], lr=0.01)

conv1_w_before = net.conv1.weight.clone().detach()
conv1_b_before = net.conv1.bias.clone().detach()
conv2_w_before = net.conv2.weight.clone().detach()
conv2_b_before = net.conv2.bias.clone().detach()

In [2]:
num_epochs = 500

for epoch in range(num_epochs):
    optimizer.zero_grad()

    noise_img_feature = net(noise_img)
    target_img_feature = net(target_data)

    loss = criterion(noise_img_feature, target_img_feature) + criterion(noise_img, target_data)

    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.6f}")

conv1_w_after = net.conv1.weight.clone().detach()
conv1_b_after = net.conv1.bias.clone().detach()
conv2_w_after = net.conv2.weight.clone().detach()
conv2_b_after = net.conv2.bias.clone().detach()

Epoch [10/500], Loss: 1.178450
Epoch [20/500], Loss: 1.012863
Epoch [30/500], Loss: 0.870394
Epoch [40/500], Loss: 0.748415
Epoch [50/500], Loss: 0.644161
Epoch [60/500], Loss: 0.554443
Epoch [70/500], Loss: 0.477392
Epoch [80/500], Loss: 0.411092
Epoch [90/500], Loss: 0.353957
Epoch [100/500], Loss: 0.304658
Epoch [110/500], Loss: 0.262092
Epoch [120/500], Loss: 0.224847
Epoch [130/500], Loss: 0.192679
Epoch [140/500], Loss: 0.165019
Epoch [150/500], Loss: 0.141240
Epoch [160/500], Loss: 0.120811
Epoch [170/500], Loss: 0.103276
Epoch [180/500], Loss: 0.088129
Epoch [190/500], Loss: 0.075223
Epoch [200/500], Loss: 0.064194
Epoch [210/500], Loss: 0.054775
Epoch [220/500], Loss: 0.046727
Epoch [230/500], Loss: 0.039825
Epoch [240/500], Loss: 0.033906
Epoch [250/500], Loss: 0.028836
Epoch [260/500], Loss: 0.024503
Epoch [270/500], Loss: 0.020801
Epoch [280/500], Loss: 0.017642
Epoch [290/500], Loss: 0.014948
Epoch [300/500], Loss: 0.012653
Epoch [310/500], Loss: 0.010699
Epoch [320/500], 

In [3]:
print("Trọng số của conv1.weight trước và sau:")
print("Trước:")
print(conv1_w_before)
print("Sau:")
print(conv1_w_after)

print("\nTrọng số cảu conv1.bias trước và sau:")
print("Trước:")
print(conv1_b_before)
print("Sau:")
print(conv1_b_after)

print("\nTrọng số conv2.weight trước và sau:")
print("Trước:")
print(conv2_w_before)
print("Sau:")
print(conv2_w_after)

print("\nTrọng số conv2.bias trước và sau:")
print("Trước:")
print(conv2_b_before)
print("Sau:")
print(conv2_b_after)

noise_img_final = noise_img.detach()
noise_feature_final = net(noise_img_final).detach()
target_feature_final = net(target_data).detach()

print("\nNoise_img ban đầu được update thành (7x7):")
print(noise_img_final[0, 0])

print("\nFeature cuối của noise_img (sau CNN):")
print(noise_feature_final[0, 0])

print("\nFeature cuối của target_img (sau CNN):")
print(target_feature_final[0, 0])

Trọng số của conv1.weight trước và sau:
Trước:
tensor([[[[-0.0025,  0.1788, -0.2743],
          [-0.2453, -0.1284,  0.0894],
          [-0.0066,  0.2643, -0.0296]]]])
Sau:
tensor([[[[-0.0025,  0.1788, -0.2743],
          [-0.2453, -0.1284,  0.0894],
          [-0.0066,  0.2643, -0.0296]]]])

Trọng số cảu conv1.bias trước và sau:
Trước:
tensor([0.0882])
Sau:
tensor([0.0882])

Trọng số conv2.weight trước và sau:
Trước:
tensor([[[[-0.1007, -0.0655, -0.3184],
          [-0.2208, -0.1374,  0.0123],
          [ 0.1318,  0.2000, -0.2260]]]])
Sau:
tensor([[[[-0.1007, -0.0655, -0.3184],
          [-0.2208, -0.1374,  0.0123],
          [ 0.1318,  0.2000, -0.2260]]]])

Trọng số conv2.bias trước và sau:
Trước:
tensor([-0.1452])
Sau:
tensor([-0.1452])

Noise_img ban đầu được update thành (7x7):
tensor([[ 2.8202e-07, -5.2328e-04,  3.2168e-05,  9.9971e-01,  4.2022e-04,
         -7.3855e-04,  1.7046e-03],
        [ 2.5076e-05,  7.8715e-05,  1.0004e+00,  1.0004e+00,  5.5809e-04,
          8.2246e-04, -

In [4]:
print(target_data)

tensor([[[[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 1., 1., 0., 0., 0.],
          [0., 1., 0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.]]]])


In [6]:
print(noise_img.detach().numpy().round(0))

[[[[ 0. -0.  0.  1.  0. -0.  0.]
   [ 0.  0.  1.  1.  0.  0. -0.]
   [ 0.  1. -0.  1.  0. -0.  0.]
   [-0. -0.  0.  1.  0.  0. -0.]
   [ 0.  0. -0.  1.  0.  0.  0.]
   [-0. -0.  0.  1.  0.  0. -0.]
   [-0.  0. -0.  1. -0. -0.  0.]]]]
