In [1]:
import numpy as np
import cv2

In [6]:
data = np.ones((4, 3, 4))
print(data)

vector = np.array([1, 1, 1])
print(vector)

result = np.einsum('ijk,j ->ik', data, vector)
print(result)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[1 1 1]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [ ]:
color_image = cv2.imread('nature.png')

vector = np.array([])