In [20]:
! pip install torch-summary

In [1]:
import torch

In [3]:
data = [1, 2, 3]
data = torch.tensor(data)
data

tensor([1, 2, 3])

In [4]:
data.shape

torch.Size([3])

In [6]:
# create a 3x3 tensor with
# with random values between 0 and 1
random_tensor = torch.rand(3, 3)

random_tensor

tensor([[0.9290, 0.5243, 0.2332],
        [0.1730, 0.8162, 0.3580],
        [0.1148, 0.6745, 0.3241]])

In [8]:
# create a 3x3 tensor with
# with random values between 0 and 1
data = torch.randn(3, 3)
data

tensor([[-1.4937,  0.0287, -1.1063],
        [ 1.6091, -1.0078,  0.6393],
        [ 0.7744,  0.3333,  0.7003]])

In [9]:
# Create a 3x3 tensor with random values
# from  a standard normal distribution : mean = 0 , std = 1

data = torch.randn(3, 3)
print(data)

tensor([[-0.8971, -0.1056,  1.1270],
        [-0.4706, -0.1821, -0.8250],
        [-0.5070, -0.2878, -1.6854]])


#### MSE loss in pytorch

In [10]:
# Compute squared difference
import torch

# Create two tensors
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
y = 5

# Compute squared difference
squared_diff = (x - y) ** 2

print(f'x:\n {x}')
print(f'y = {y}')
print(f'squared_diff:\n {squared_diff}')

x:
 tensor([1., 2., 3., 4.])
y = 5
squared_diff:
 tensor([16.,  9.,  4.,  1.])


In [11]:
# Compute squared difference
import torch

# Create two tensors
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
y = torch.tensor([5.0, 5.0, 5.0, 5.0])

# Compute squared difference
loss_fn = torch.nn.MSELoss()
mse = loss_fn(x, y)

print(f'x:\n {x}')
print(f'y = {y}')
print(f'mse:\n {mse}')

x:
 tensor([1., 2., 3., 4.])
y = tensor([5., 5., 5., 5.])
mse:
 7.5


#### Concatnate tensors

In [12]:
# Concatenate tensors
import torch

# Create two tensors
x = torch.tensor([[1, 2],
                  [3, 4]])
y = torch.tensor([[3, 4],
                  [5, 6]])

# Concat tensors along the first dimension
tensor1 = torch.cat((x, y), dim=0)
print(f'Tensor1:\n {tensor1}')

# Concat tensors along the second dimension
tensor2 = torch.cat((x, y), dim=1)
print(f'Tensor2:\n {tensor2}')

Tensor1:
 tensor([[1, 2],
        [3, 4],
        [3, 4],
        [5, 6]])
Tensor2:
 tensor([[1, 2, 3, 4],
        [3, 4, 5, 6]])


#### arg max
- dim = 0 : theo cột
- dim = 1 : theo hàng

In [13]:
# argmax
import torch

# Creates a 3x2 tensor
data = torch.tensor([[3, 4],
                     [4, 2],
                     [1, 1]])
print(f'data:\n {data}')

# Compute argmax across the rows (dimension 0)
argmax_dim0 = torch.argmax(data, dim=0)
print(f'argmax along dim 0:\n {argmax_dim0}')

# Compute argmax across the columns (dimension 1)
argmax_dim1 = torch.argmax(data, dim=1)
print(f'argmax along dim 1:\n {argmax_dim1}')

data:
 tensor([[3, 4],
        [4, 2],
        [1, 1]])
argmax along dim 0:
 tensor([1, 0])
argmax along dim 1:
 tensor([1, 0, 0])


#### auto gradient

In [16]:
x = torch.tensor(2.0, requires_grad= True)

y = x ** 2
z = 3*y + 2

print(f'z::{z}')

z.backward()

print(f"Gradient of z w.r.t x : {x.grad}")

z::14.0
Gradient of z w.r.t x : 12.0


#### Linear regresion

In [18]:
x = torch.tensor([6.7])
print(x)

w = -0.34
b = 0.04

y_hat = x*w + b
print(y_hat)

tensor([6.7000])
tensor([-2.2380])


In [19]:
import torch.nn as nn
linear_model = nn.Linear(1, 1)

linear_model.bias.data.fill_(0.04)
linear_model.weight.data.fill_(-0.34)

print(linear_model.bias)
print(linear_model.weight)

y_hat = linear_model(x)
print(y_hat)

Parameter containing:
tensor([0.0400], requires_grad=True)
Parameter containing:
tensor([[-0.3400]], requires_grad=True)
tensor([-2.2380], grad_fn=<ViewBackward0>)


In [26]:
from torchsummary import summary 

model = nn.Sequential(
    nn.Linear(in_features=2, out_features=2)
)
summary(model, input_size = (1,))

Layer (type:depth-idx)                   Param #
├─Linear: 1-1                            6
Total params: 6
Trainable params: 6
Non-trainable params: 0


Layer (type:depth-idx)                   Param #
├─Linear: 1-1                            6
Total params: 6
Trainable params: 6
Non-trainable params: 0

In [29]:
x = torch.tensor([6.7])

In [30]:
model = nn.Sequential(
    nn.Linear(1, 1)
)

output = model(x)
print(x)

tensor([6.7000])


In [33]:
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [34]:
model.parameters()

<generator object Module.parameters at 0x000001EC6F088890>

In [36]:
import torch
import torch.nn as nn

# Đầu ra từ mô hình (logits)
logits = torch.tensor([0.2, -1.5, 2.0])
target = torch.tensor([1.0, 0.0, 1.0])

# Áp dụng Sigmoid trước khi đưa vào BCELoss
sigmoid_output = torch.sigmoid(logits)
loss_fn = nn.BCELoss()
loss = loss_fn(sigmoid_output, target)
print(f"Loss with BCELoss: {loss.item()}")

Loss with BCELoss: 0.3088267743587494


In [35]:
import torch
import torch.nn as nn

# Đầu ra từ mô hình (logits)
logits = torch.tensor([0.2, -1.5, 2.0])
target = torch.tensor([1.0, 0.0, 1.0])

# Sử dụng BCEWithLogitsLoss, không cần áp dụng Sigmoid
loss_fn = nn.BCEWithLogitsLoss()
loss = loss_fn(logits, target)
print(f"Loss with BCEWithLogitsLoss: {loss.item()}")

Loss with BCEWithLogitsLoss: 0.3088267743587494
